# Generated by Django 4.2.5 on 2023-09-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='null.jpeg', upload_to='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='tb_register',
            name='image',
        ),
    ]
