# Generated by Django 4.2.5 on 2023-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapi', '0004_alter_tb_resume_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tb_resume',
            name='skill',
        ),
    ]
