# Generated by Django 4.2.5 on 2023-10-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapi', '0005_tb_skill_remove_tb_resume_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_resume',
            name='resume_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapi.tb_register'),
        ),
        migrations.AddField(
            model_name='tb_skill',
            name='skill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapi.tb_register'),
        ),
    ]
