# Generated by Django 4.2.5 on 2023-10-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapi', '0006_tb_resume_resume_id_tb_skill_skill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_resume',
            old_name='resume_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='tb_skill',
            old_name='skill_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='tb_skill',
            name='resume_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapi.tb_resume'),
        ),
    ]
