# Generated by Django 4.2.5 on 2023-10-04 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapi', '0008_remove_tb_skill_resume_id_remove_tb_skill_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_skill',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapi.tb_register'),
        ),
    ]
