# Generated by Django 4.2.5 on 2023-10-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapi', '0009_tb_skill_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_register',
            name='dob',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_register',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_register',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_register',
            name='yop',
            field=models.CharField(default='', max_length=100),
        ),
    ]
