# Generated by Django 4.2.5 on 2023-10-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapi', '0011_tb_register_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_register',
            name='status',
        ),
    ]
