# Generated by Django 4.2.5 on 2023-10-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapi', '0012_remove_tb_register_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_resume',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tb_skill',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='tb_register',
        ),
        migrations.DeleteModel(
            name='tb_resume',
        ),
        migrations.DeleteModel(
            name='tb_skill',
        ),
    ]
