# Generated by Django 4.2.5 on 2023-09-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_cmpny_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('uname', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('adrs', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
