# Generated by Django 4.2.5 on 2023-09-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetector', '0002_tb_cmpny_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_details',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_details',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_details',
            name='job',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tb_details',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tb_details',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tb_details',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tb_details',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tb_details',
            name='skill',
            field=models.CharField(default='', max_length=100),
        ),
    ]
