# Generated by Django 4.2.5 on 2023-10-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetector', '0003_tb_details_date_tb_details_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_details',
            name='cmpny_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumedetector.tb_cmpny_register'),
        ),
    ]
