# Generated by Django 4.2.5 on 2023-10-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetector', '0004_tb_details_cmpny_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_details',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
