# Generated by Django 4.2.5 on 2023-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetector', '0006_remove_tb_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_details',
            name='status',
            field=models.CharField(default='applied', max_length=100),
        ),
    ]
