# Generated by Django 4.2.5 on 2023-10-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetector', '0008_tb_register_tb_skill_tb_resume_tb_details_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_details',
            name='user_id',
        ),
    ]
