# Generated by Django 4.2.5 on 2023-10-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetector', '0009_remove_tb_details_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_details',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
