# Generated by Django 4.2.5 on 2023-10-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetector', '0011_tb_details_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_job_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=100)),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumedetector.tb_details')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumedetector.tb_register')),
            ],
        ),
    ]
