# Generated by Django 4.2.5 on 2023-10-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetector', '0012_tb_job_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_details',
            name='user_id',
        ),
    ]
