# Generated by Django 4.2.5 on 2023-10-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetector', '0015_tb_job_application_cmpny_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_cmpny_register',
            name='utype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
